name: ex
description: EX a new chat application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  image_picker:
  intl:
  flutter_snake_navigationbar:
  firebase_storage:
  easy_alert:
  clipboard:
  http:
  shared_preferences:
  provider:
  cloud_firestore:
  firebase_core:
  firebase_messaging:
  url_launcher:
  share:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/right-arrow.png
    - assets/images/right-arrow-onboarding.png
    - assets/images/logo.png
    - assets/images/no-message.png
    - assets/images/conversation.png
    - assets/images/log-in.png
    - assets/images/privacy.png

  fonts:
    - family: Bosca
      fonts:
        - asset: assets/fonts/Bosca/Bosca-Regular.ttf
        - asset: assets/fonts/Bosca/Bosca-Light.ttf
        - asset: assets/fonts/Bosca/Bosca-Bold.ttf
        - asset: assets/fonts/Bosca/Bosca-Medium.ttf
  #         style: italic
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
        - asset: assets/fonts/Cairo/Cairo-ExtraLight.ttf
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
  #         weight: 700
